version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[dependencies]"
    groups:
      MCP:
        patterns:
          - "ModelContextProtocol.*"
      DevOps:
        patterns:
          - "Microsoft.TeamFoundationServer.*"
          - "Microsoft.VisualStudio.*"
      platform:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.*"
          - "System.*"
      test:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit.*"
          - "coverlet"
          - "coverlet.*"
